#!/usr/bin/env bash
set -euo pipefail

# RCON の設定
export MCRCON_HOST="127.0.0.1"
export MCRCON_PORT="25575"
export MCRCON_PASS='Password'

url="https://api.valine3g-dev.f5.si/whitelist.json"
dest="./whitelist.json"
lock="./lock"
tmp="$(mktemp)"

exec 9>"$lock"
flock -n 9 || exit 0

http_code="$(
  if [ -f "$dest" ]; then
    curl -fsS -z "$dest" -R -o "$tmp" -w '%{http_code}' "$url"
  else
    curl -fsS -R -o "$tmp" -w '%{http_code}' "$url"
  fi
)"

case "$http_code" in
  200)
    mv "$tmp" "$dest"
    ./mcrcon "whitelist reload"
    ;;
  304)
    rm -f "$tmp"
    ;;
esac
