

name: Build Modpack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip dist folder
        run: |
          ZIP_NAME="latest.mrpack"
          cd pack
          zip -r "../$ZIP_NAME" .
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build
          files: ${{ env.ZIP_NAME }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
